# fly.toml app configuration file generated for go-example-proud-resonance-3596 on 2024-09-03T02:14:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-example-proud-resonance-3596'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
